### ISSUE TITLE
Supporting zoom-in and zoom-out with pinch gestures.

### ISSUE THREAD

**Issue by shipunyc** [ldn0x7dc/react-native-gallery#1]
This will be a very nice and useful feature

**Comment by ldn0x7dc** [comment]
@shipunyc 
This feature is available from first release. 
Seems you encountered a bug? 
Could you post your react-native version and a simple demo here?
Your test device is also welcome.

**Comment by shipunyc** [comment]
Hi ldn0x7dc,

I just figured out that it actually works, but in the IOS emulator, I need to drag the image a bit first, then use "ALT" to add another "finger" to pinch.

If I pinch directly, the image won't zoom

I think in real device this won't be a problem.

**Comment by ldn0x7dc** [comment]
@shipunyc 
Yes, that's it. So I'm closing this issue.
