### ISSUE TITLE
Is there a way to set current page of the gallery?

### ISSUE THREAD

**Issue by winglight** [ldn0x7dc/react-native-gallery#12]
I tried to set the field "currentPage" of the gallery outside of the component, unfortunately, that's failed.

**Comment by ldn0x7dc** [comment]
@winglight 
You can use `gallery.getViewPagerInstance().setPage(page)`.

**Comment by winglight** [comment]
It works fine! Thanks a lot!

**Comment by winglight** [comment]
Sometimes after invoking setPage and swipe to next page, RN will throw an error:
`ExceptionsManager.js:61 Cannot read property 'onResponderGrant' of undefined` at line 112 of Gallery.js.

**Comment by winglight** [comment]
Finally, it works. So I close it.

**Comment by ducpt2** [comment]
I try to use setPage(page) but it seem not work. Can you show me how to use it? I want to create button backward and forward. Thanks.
