### ISSUE TITLE
onSingleTapConfirmed,onGalleryStateChanged

### ISSUE THREAD

**Issue by xufengzi** [ldn0x7dc/react-native-gallery#3]
onSingleTapConfirmed,onGalleryStateChanged 这两个事件不起作用，好像没有触发

**Comment by ldn0x7dc** [comment]
@xufengzi 
能不能提供一下RN版本、测试机信息以及一个简单的代码摘录？

**Comment by xufengzi** [comment]
我下载的的是你上面的Demo 在6p 上面  
onSingleTapConfirmed={() => {
          alert(" onSingleTapConfirmed");
          this.toggleCommentBox();
        }}
          onGalleryStateChanged={(idle) => {
           alert(idle);
          if(!idle) {
            this.hideCommentBox();
          }
        }}

alert() 没有弹出信息

**Comment by ldn0x7dc** [comment]
@xufengzi 
问题原因是Demo仍然使用的是0.0.13，而onSingleTapConfirmed等特性是在0.0.14加进来的。
所以在Demo里安装最新版的react-native-gallery就OK了。

**Comment by xufengzi** [comment]
谢谢
